### PR TITLE
added initial boiler-plate

### PR DESCRIPTION
**Pull request by tigawanna**
hey saw your project and felt like helping

### CODE REVIEW

**Comment by Ephantuz** [comment]
urm, not really until we talk about it, cause it's a bit different to what I want to create.

But instead you can contribute on my other goalsApp-api repository, but not this one.

**Comment by Ephantuz** [comment]
We can work together on the other repository " mygoalsapp-api " if you don't mind.  This one it's a bit personal cause i've already done pretty much of everything speaking of front-end. Now am working on backend.

and hey! we follow each other i believe, If not. please follow me and ill follow back.

**Comment by tigawanna** [comment]
Sure

**Comment by Ephantuz** [comment]
I also realized your way of handling routes it's way different to mine.

Let's work on the other repository and give opinions on each other.

Can I have your number please?

**Comment by tigawanna** [comment]
O790984481

**Comment by Ephantuz** [comment]
Dennis... Right?

**Pull request merged**
